config/routes.rb
Rails.application.routes.draw do
  root 'topics#root'

#  get 'my_users', to: 'users#my_users'
#  get 'new_user', to:'users#new_user'
#  post 'create_user', to: 'users#create_user'
#  get 'edit_my_user/:id', to: 'users#edit_my_user'
#  post 'edit_my_user/modify_user', to: 'users#modify_user'
  get 'edit_my_users', to: 'users#edit_my_users'
  post 'modify_my_users', to: 'users#modify_my_users'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Articles
  #get 'my_articles', to: 'articles#my_articles'
  #get 'new_article', to: 'articles#new_article'
#  get 'my_article/:id', to: 'articles#my_article'
  #get 'edit_my_article/:id', to: 'articles#edit_my_article'
#  post 'edit_my_article/modify_article', to: 'articles#modify_article'
#post 'create_article', to: 'articles#create_article'
  resources :articles do
    resources :comments
  end
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, :body, presence: true
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { maximum: 30, minimum: 2 }, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true, length: { maximum: 20, minimum: 2 }
end

app/models/orders.rb
class Orders < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :body, :category_ids => []))
    if @article.save #=> true or false
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new({article_id: params[:id]})
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :body))
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(params.require(:comment).permit(:body))

    if @comment.save
      redirect_to article_path(article)
    else
      render 'articles/show'
        #si article tiene errores
        #  muestra el view again
        #fin
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController <ApplicationController
  def root
    

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(params.require(:user).permit(:fname, :lname, :age))
    user.save
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(params.require(:user).permit(:fname, :lname, :age))
    redirect_to users_path
  end

  def edit_my_users
  end

  def modify_my_users
    params.permit![:users].each do |id, attributes|
      user = User.find(id)
      user.update(attributes)
    end
    redirect_to "/my_users"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if article.errors.any? %>
  <ul>
    <% article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for article do |f| %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <br>
  <%= f.text_area :body, size: "60x12" %>
  <br>
  <%= f.label :categories %>
  <br>
  <%= collection_check_boxes(:article, :category_ids, Category.all, :id, :name) %>
  <br>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'articles/form', article: @article %>

app/views/articles/index.html.erb
<%= link_to 'New article', new_article_path %>


<% @articles.each do |article| %>
<br>
<br>
  <% article.categories.each do |c| %>
    <span><%= c.name + ' ' %><span>
  <% end %>
  <%= link_to article_path(article) do %>
    <h1><%= article.title %></h1>
  <% end %>
  <p><%=article.body %></p>
<% end  %>

app/views/articles/my_article.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

app/views/articles/my_articles.html.erb
<% @articles.each do |article| %>
  <h1><%= article.title %></h1>
  <p><%=article.body %></p>
<% end  %>

app/views/articles/my_users.html.erb
<h1>USER LIST</h1>
<a href="/edit_my_users">Edit</a>

<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
    <th>Created at</th>
    <th>Updated at</th>
  </tr>
  <% User.all.each do |user| %>
    <tr>
      <td><%= user.fname %></td>
      <td><%= user.lname %></td>
      <td><%= user.age %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>

    </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<!--
 <form action="create_article" method="post">  <label for="title">Title</label>
  <br>
  <input type="text" name="title" value="" placeholder="Titulo">
  <br>
  <label for="body">Body</label>
  <br>
  <textarea name="body" rows="8" cols="80" placeholder="Body"></textarea>
  <br>
  <input type="submit" name="" value="Create Article">
  <br>
</form>
-->



<%= render 'articles/form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<%= link_to 'Edit', edit_article_path(@article) %>


<!-- Si hay algun error en los comentarios
  muestra los errores de los comentarios
fin -->

<h2>Comments</h2>

<% if @comment.errors.any? %>
  <ul>
    <% @comment.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<br>
<%= form_for([@article, @comment]) do |f| %>
  <%= f.label :body %>
  <br>
  <%= f.text_area :body, size: "60x12" %>
  <br>
  <%= f.submit %>
  <br>
  <br>
<% end %>

<% @article.comments.each do |c| %>
  <%= c.body %>
  <br>
  <%= c.created_at %>
  <br>
  <br>
<% end %>

app/views/articles/show.html.erbs.html.erb
<% @articles.each do |article| %>
  <h1><%= article.title %></h1>
  <p><%=article.body %></p>
<% end  %>

app/views/categories/index.html.erb
<%= link_to "New Category", new_category_path %>

<% @categories.each do |c| %>
  <h1> <%= c.name %> </h1>
<% end %>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <ul>
    <% @category.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @category do |c| %>
  <%= c.label :name %>
  <%= c.text_field :name %>
  <%= c.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/root.html.erb
<h1>
<%= link_to 'Articles', articles_path %>
</h1>
<h1>
<%= link_to 'Users', users_path %>
</h1>
<h1>
  <%= link_to 'Categories', categories_path %>
</h1>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label 'First Name', :fname %>
  <br>
  <%= f.text_field :fname %>
  <br>
  <%= f.label 'Last Name', :lname %>
  <br>
  <%= f.text_field :lname %>
  <br>
  <%= f.label 'Age', :age %>
  <br>
  <%= f.text_field :age %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'users/form', user: @user %>

app/views/users/edit_my_users.html.erb
<h1>USER LIST</h1>

<form action="modify_my_users" method="post">
  <input type="submit" name="" value="Submit">
  <table style="width:100%">
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Age</th>
      <th>Created at</th>
      <th>Updated at</th>
    </tr>
    <% User.all.each do |user| %>
      <tr>
        <td> <input type="text" name="[users][<%= user.id %>][fname]" value="<%= user.fname %>"> </td>
        <td> <input type="text" name="[users][<%= user.id %>][lname]" value="<%= user.lname %>"></td>
        <td> <input type="text" name="[users][<%= user.id %>][age]" value="<%= user.age %>"></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
      </tr>
    <% end %>
  </table>

</form>

app/views/users/index.html.erb
<h1>USER LIST</h1>
<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Modify User</th>
  </tr>
  <% User.all.each do |user| %>
    <tr>
      <td><%= user.fname %></td>
      <td><%= user.lname %></td>
      <td><%= user.age %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>
      <td><a href="/users/<%=user.id%>/edit"><%= user.id%></a></td>


    </tr>
  <% end %>
</table>

app/views/users/my_users.html.erb
<h1>USER LIST</h1>

<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
    <th>Created at</th>
    <th>Updated at</th>
  </tr>
  <% User.all.each do |user| %>
    <tr>
      <td><%= user.fname %></td>
      <td><%= user.lname %></td>
      <td><%= user.age %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>
    </tr>
  <% end %>

</table>

app/views/users/new.html.erb
<%= render 'users/form', user: @user %>

app/views/users/new_user.html.erb
<form action="create_user" method="post">
  <label for="fname">What's your name</label>
  <br>
  <input type="text" name="fname" value="" placeholder="Pedro">
  <br>
  <label for="lname">What's your lastname</label>
  <br>
  <input type="text" name="lname" value="" placeholder="Perez">
  <br>
  <label for="age">Age</label>
  <br>
  <input type="text" name="age" value="">
  <br>
  <input type="submit" name="" value="Create your account">

</form>